const gwentCardData = [
    // --- CARTES NEUTRES (ID 1 à 20) - 20 Cartes ---
    { id: 1, nom: "Geralt de Riv", royaume: "Neutre", force: 15, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Un Héros. Intouchable par la Meteo et Incinération.", isHero: true },
    { id: 2, nom: "Ciri", royaume: "Neutre", force: 15, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Un Héros. Intouchable par la Meteo et Incinération.", isHero: true },
    { id: 3, nom: "Yennefer de Vengerberg", royaume: "Neutre", force: 7, type: "Unité", ligne: ["Ranged"], capacite: "Médecin", max_copies: 1, description: "Un Héros. Médecin : Ramène une unité non-Héros de la défausse.", isHero: true },
    { id: 4, nom: "Triss Merigold", royaume: "Neutre", force: 7, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 1, description: "Un Héros. Ralliement : Pioche une carte Unité de votre deck et la joue immédiatement.", isHero: true },
    { id: 5, nom: "Avallac'h", royaume: "Neutre", force: 0, type: "Unité", ligne: ["Siege"], capacite: "Espion", max_copies: 1, description: "Un Héros. Espion : Placé chez l'adversaire, piochez 2 cartes.", isHero: true },
    { id: 6, nom: "Villentretenmerth", royaume: "Neutre", force: 7, type: "Unité", ligne: ["Melee"], capacite: "Incinération Temporisée", max_copies: 1, description: "Détruit les unités non-Héros ennemies ayant la plus haute force après 3 tours.", isHero: false },
    { id: 7, nom: "Vésémir", royaume: "Neutre", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 1, description: "Ralliement : Pioche une carte Unité de votre deck et la joue immédiatement.", isHero: false },
    { id: 8, nom: "Zoltan Chivay", royaume: "Neutre", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 1, description: "Ralliement : Pioche une carte Unité de votre deck et la joue immédiatement.", isHero: false },
    { id: 9, nom: "Vieux Sabot", royaume: "Neutre", force: 0, type: "Unité", ligne: ["Melee"], capacite: "Espion", max_copies: 1, description: "Espion : Placé chez l'adversaire, piochez 2 cartes.", isHero: false },
    { id: 10, nom: "Jaskier", royaume: "Neutre", force: 2, type: "Unité", ligne: ["Ranged"], capacite: "Ralliement", max_copies: 1, description: "Ralliement : Pioche une carte Unité de votre deck et la joue immédiatement.", isHero: false },
    
    // Cartes Spéciales
    { id: 11, nom: "Incinération", royaume: "Neutre", force: 0, type: "Spécial", ligne: "Amélioration", capacite: "Incinération", max_copies: 3, description: "Détruit la ou les cartes Unité non-Héros avec la plus haute force sur le plateau.", isHero: false },
    { id: 12, nom: "Leurre", royaume: "Neutre", force: 0, type: "Spécial", ligne: "Amélioration", capacite: "Leurre", max_copies: 3, description: "Échange cette carte avec une unité alliée non-Héros du plateau pour la ramener en main.", isHero: false },
    { id: 13, nom: "Cor de Chasse", royaume: "Neutre", force: 0, type: "Spécial", ligne: "Amélioration", capacite: "Cor de Chasse", max_copies: 3, description: "Double la force des unités non-Héros dans une rangée choisie.", isHero: false },
    
    // Cartes Meteo (ligne en string car elles affectent le plateau globalement)
    { id: 14, nom: "Froid Mordant", royaume: "Neutre", force: 0, type: "Spécial", ligne: "Melee", capacite: "Meteo", max_copies: 3, description: "Réduit toutes les unités non-Héros de la rangée Mêlée à 1 de force.", isHero: false },
    { id: 15, nom: "Brouillard Impénétrable", royaume: "Neutre", force: 0, type: "Spécial", ligne: "Ranged", capacite: "Meteo", max_copies: 3, description: "Réduit toutes les unités non-Héros de la rangée Distance à 1 de force.", isHero: false },
    { id: 16, nom: "Pluie Torrentielle", royaume: "Neutre", force: 0, type: "Spécial", ligne: "Siege", capacite: "Meteo", max_copies: 3, description: "Réduit toutes les unités non-Héros de la rangée Siège à 1 de force.", isHero: false },
    { id: 17, nom: "Temps Dégagé", royaume: "Neutre", force: 0, type: "Spécial", ligne: "Amélioration", capacite: "Temps Dégagé", max_copies: 3, description: "Annule tous les effets Meteo actifs sur le plateau.", isHero: false },
    
    // Autres Héros
    { id: 18, nom: "Eskel", royaume: "Neutre", force: 10, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Un Héros. Intouchable par la Meteo et Incinération.", isHero: true },
    { id: 19, nom: "Lambert", royaume: "Neutre", force: 10, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Un Héros. Intouchable par la Meteo et Incinération.", isHero: true },
    { id: 20, nom: "Régis", royaume: "Neutre", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Médecin", max_copies: 1, description: "Ramène une carte Unité non-Héros de la défausse. Unité unique.", isHero: false },

    // --- ROYAUMES DU NORD (ID 21 à 56) - 36 Cartes ---
    { id: 21, nom: "Foltest le Féroce", royaume: "Royaumes du Nord", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Meteo)", max_copies: 1, description: "Chef. Pioche une carte Meteo et la joue immédiatement.", isHero: true },
    { id: 22, nom: "Foltest le Sanguinaire", royaume: "Royaumes du Nord", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Temps Dégagé)", max_copies: 1, description: "Chef. Annule tous les effets Meteo sur la ligne de Mêlée.", isHero: true },
    { id: 23, nom: "Foltest le Vétéran", royaume: "Royaumes du Nord", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Incinération)", max_copies: 1, description: "Chef. Détruit toutes les cartes de Siège ennemies ayant une force de 10 ou plus.", isHero: true },
    { id: 24, nom: "Foltest le Loyal", royaume: "Royaumes du Nord", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Ralliement)", max_copies: 1, description: "Chef. Ralliement : Pioche une carte Unité et la joue immédiatement.", isHero: true },
    { id: 25, nom: "Vernon Roche", royaume: "Royaumes du Nord", force: 10, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Un Héros.", isHero: true },
    { id: 26, nom: "Philippa Eilhart", royaume: "Royaumes du Nord", force: 10, type: "Unité", ligne: ["Ranged"], capacite: "Héros", max_copies: 1, description: "Un Héros.", isHero: true },
    { id: 27, nom: "Thaler", royaume: "Royaumes du Nord", force: 1, type: "Unité", ligne: ["Siege"], capacite: "Espion", max_copies: 1, description: "Espion : Placé chez l'adversaire, piochez 2 cartes.", isHero: false },
    { id: 28, nom: "Stennis de Falt", royaume: "Royaumes du Nord", force: 5, type: "Unité", ligne: ["Siege"], capacite: "Ralliement", max_copies: 1, description: "Ralliement : Pioche une carte Unité de votre deck et la joue immédiatement.", isHero: false },
    { id: 29, nom: "Prince Stennis", royaume: "Royaumes du Nord", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Espion", max_copies: 1, description: "Espion : Placé chez l'adversaire, piochez 2 cartes.", isHero: false }, 
    { id: 30, nom: "Dijkstra", royaume: "Royaumes du Nord", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Espion", max_copies: 1, description: "Espion : Placé chez l'adversaire, piochez 2 cartes.", isHero: false },
    { id: 31, nom: "Fantassin Redanien", royaume: "Royaumes du Nord", force: 1, type: "Unité", ligne: ["Melee"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel : Double la force de toutes les cartes du même nom.", isHero: false },
    { id: 32, nom: "Catapulte", royaume: "Royaumes du Nord", force: 8, type: "Unité", ligne: ["Siege"], capacite: "Lien Fraternel", max_copies: 2, description: "Lien Fraternel : Double la force de toutes les cartes du même nom.", isHero: false },
    { id: 33, nom: "Sorcier de Kaedwen", royaume: "Royaumes du Nord", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel : Double la force de toutes les cartes du même nom.", isHero: false },
    { id: 34, nom: "Sorceleur de Temeria", royaume: "Royaumes du Nord", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Médecin", max_copies: 1, description: "Médecin : Ramène une carte Unité non-Héros de la défausse.", isHero: false },
    { id: 35, nom: "Archer Aedirnien", royaume: "Royaumes du Nord", force: 3, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 36, nom: "Chevalier de la Flamme Éternelle", royaume: "Royaumes du Nord", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 37, nom: "Infanterie Légère", royaume: "Royaumes du Nord", force: 2, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 38, nom: "Trébuchet", royaume: "Royaumes du Nord", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 39, nom: "Bélier", royaume: "Royaumes du Nord", force: 4, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 40, nom: "Baliste Naine", royaume: "Royaumes du Nord", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 41, nom: "Canon", royaume: "Royaumes du Nord", force: 8, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 42, nom: "Fantassin Témérien", royaume: "Royaumes du Nord", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 43, nom: "Arbalétrier de la Garde", royaume: "Royaumes du Nord", force: 4, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 44, nom: "Bâtisse de Siège", royaume: "Royaumes du Nord", force: 1, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 45, nom: "Escorte Royale", royaume: "Royaumes du Nord", force: 2, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 46, nom: "Éclaireur des Temerians", royaume: "Royaumes du Nord", force: 1, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 47, nom: "Garde de la Lyrie", royaume: "Royaumes du Nord", force: 3, type: "Unité", ligne: ["Melee"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel : Double la force de toutes les cartes du même nom.", isHero: false },
    { id: 48, nom: "Garde du Nord", royaume: "Royaumes du Nord", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Morale", max_copies: 2, description: "Morale : Donne +1 de force à toutes les autres unités de sa rangée.", isHero: false },
    { id: 49, nom: "Guerrier de Kaedwen", royaume: "Royaumes du Nord", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base forte.", isHero: false },
    { id: 50, nom: "Bélier de guerre", royaume: "Royaumes du Nord", force: 5, type: "Unité", ligne: ["Siege"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel : Double la force de toutes les cartes du même nom.", isHero: false },
    { id: 51, nom: "Ingénieur Aedirnien", royaume: "Royaumes du Nord", force: 3, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 52, nom: "Arbalète lourde", royaume: "Royaumes du Nord", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 53, nom: "Brigade de Temeria", royaume: "Royaumes du Nord", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 54, nom: "Éclaireur de la Garde", royaume: "Royaumes du Nord", force: 1, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 55, nom: "Canon à roquettes", royaume: "Royaumes du Nord", force: 10, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 1, description: "Unité de base très forte.", isHero: false },
    { id: 56, nom: "Tireur d'élite de la Couronne", royaume: "Royaumes du Nord", force: 2, type: "Unité", ligne: ["Ranged"], capacite: "Morale", max_copies: 2, description: "Morale : Donne +1 de force à toutes les autres unités de sa rangée.", isHero: false },

    // --- SCOIA'TAEL (ID 57 à 89) - 33 Cartes ---
    { id: 57, nom: "Francesca Findabair (F)", royaume: "Scoia'tael", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Médecin)", max_copies: 1, description: "Chef. Ramène une carte de la défausse dans votre main.", isHero: true },
    { id: 58, nom: "Francesca Findabair (R)", royaume: "Scoia'tael", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Espion)", max_copies: 1, description: "Chef. Espion : Regardez 3 cartes de votre deck et jouez-en une.", isHero: true },
    { id: 59, nom: "Eithné (F)", royaume: "Scoia'tael", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Cor de Chasse)", max_copies: 1, description: "Chef. Double la force de toutes les cartes d'une rangée.", isHero: true },
    { id: 60, nom: "Eithné (R)", royaume: "Scoia'tael", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Ralliement)", max_copies: 1, description: "Chef. Ralliement : Pioche une carte Unité et la joue immédiatement.", isHero: true },
    { id: 61, nom: "Geralt de Riv (ST)", royaume: "Scoia'tael", force: 15, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Héros. (Neutre - Duplication).", isHero: true },
    { id: 62, nom: "Ciri (ST)", royaume: "Scoia'tael", force: 15, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Héros. (Neutre - Duplication).", isHero: true },
    { id: 63, nom: "Iorveth", royaume: "Scoia'tael", force: 10, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Un Héros.", isHero: true },
    { id: 64, nom: "Saskia", royaume: "Scoia'tael", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Héros", max_copies: 1, description: "Un Héros. Ralliement.", isHero: true },
    { id: 65, nom: "Dennis Cranmer", royaume: "Scoia'tael", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 1, description: "Ralliement : Pioche une carte Unité de votre deck et la joue immédiatement.", isHero: false },
    { id: 66, nom: "Zoltan Chivay (ST)", royaume: "Scoia'tael", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 1, description: "Ralliement : (Neutre - Duplication).", isHero: false },
    
    // CARTES AGILES (Double Ligne)
    { id: 67, nom: "Vanguard des Scoia'tael", royaume: "Scoia'tael", force: 4, type: "Unité", ligne: ["Melee", "Ranged", "Agile"], capacite: "Lien Fraternel", max_copies: 3, description: "Agile. Lien Fraternel.", isHero: false },
    { id: 68, nom: "Fantassin Nain", royaume: "Scoia'tael", force: 5, type: "Unité", ligne: ["Melee", "Ranged", "Agile"], capacite: "Lien Fraternel", max_copies: 3, description: "Agile. Lien Fraternel.", isHero: false },
    { id: 69, nom: "Commando des Vrihedd", royaume: "Scoia'tael", force: 4, type: "Unité", ligne: ["Melee", "Ranged", "Agile"], capacite: "Lien Fraternel", max_copies: 3, description: "Agile. Lien Fraternel.", isHero: false },
    { id: 70, nom: "Vétéran Nain", royaume: "Scoia'tael", force: 5, type: "Unité", ligne: ["Melee", "Ranged", "Agile"], capacite: "Médecin", max_copies: 2, description: "Agile. Médecin.", isHero: false },
    { id: 71, nom: "Pisteuse Nain", royaume: "Scoia'tael", force: 4, type: "Unité", ligne: ["Ranged", "Siege", "Agile"], capacite: "Ralliement", max_copies: 2, description: "Agile. Ralliement.", isHero: false },
    { id: 72, nom: "Eclaireur des Vrihedd", royaume: "Scoia'tael", force: 2, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 73, nom: "Archer Elfe", royaume: "Scoia'tael", force: 3, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 74, nom: "Sentinelle Elfe", royaume: "Scoia'tael", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 75, nom: "Bélier Nain", royaume: "Scoia'tael", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 76, nom: "Commando du Lion", royaume: "Scoia'tael", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 77, nom: "Baliste Naine (ST)", royaume: "Scoia'tael", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 78, nom: "Sorcier Elfe", royaume: "Scoia'tael", force: 3, type: "Unité", ligne: ["Ranged"], capacite: "Morale", max_copies: 2, description: "Morale : Donne +1 de force à toutes les autres unités de sa rangée.", isHero: false },
    { id: 79, nom: "Guerrier des Montagnes", royaume: "Scoia'tael", force: 8, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base forte.", isHero: false },
    { id: 80, nom: "Héros Elfe", royaume: "Scoia'tael", force: 10, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 1, description: "Unité de base forte (unique).", isHero: false },
    { id: 81, nom: "Archer à Long Arc", royaume: "Scoia'tael", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 82, nom: "Cavalerie Légère", royaume: "Scoia'tael", force: 3, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 83, nom: "Ingénieur Nain", royaume: "Scoia'tael", force: 4, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 84, nom: "Éclaireur Nain", royaume: "Scoia'tael", force: 1, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 85, nom: "Sentinelle des Bois", royaume: "Scoia'tael", force: 2, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 86, nom: "Trébuchet Nain", royaume: "Scoia'tael", force: 7, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 87, nom: "Bélier de Siège", royaume: "Scoia'tael", force: 5, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 88, nom: "Défenseur Elfe", royaume: "Scoia'tael", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 89, nom: "Chasseur Elfe", royaume: "Scoia'tael", force: 4, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },

    // --- NILFGAARD (ID 90 à 127) - 38 Cartes ---
    { id: 90, nom: "Emhyr var Emreis (Le Magnifique)", royaume: "Nilfgaard", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Médecin)", max_copies: 1, description: "Chef. Ramène une carte de la défausse dans votre main.", isHero: true },
    { id: 91, nom: "Emhyr var Emreis (Le Conquérant)", royaume: "Nilfgaard", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Espion)", max_copies: 1, description: "Chef. Espion : Regardez 3 cartes de votre deck et jouez-en une.", isHero: true },
    { id: 92, nom: "Morvran Voorhis (L'Impassible)", royaume: "Nilfgaard", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Incinération)", max_copies: 1, description: "Chef. Détruit toutes les cartes de Mêlée ennemies ayant une force de 10 ou plus.", isHero: true },
    { id: 93, nom: "Morvran Voorhis (Le Féroce)", royaume: "Nilfgaard", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Ralliement)", max_copies: 1, description: "Chef. Ralliement : Pioche une carte Unité et la joue immédiatement.", isHero: true },
    { id: 94, nom: "Geralt de Riv (NG)", royaume: "Nilfgaard", force: 15, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Héros. (Neutre - Duplication).", isHero: true },
    { id: 95, nom: "Ciri (NG)", royaume: "Nilfgaard", force: 15, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Héros. (Neutre - Duplication).", isHero: true },
    // AGILE (Héros)
    { id: 96, nom: "Vattier de Rideaux", royaume: "Nilfgaard", force: 4, type: "Unité", ligne: ["Ranged", "Siege", "Agile"], capacite: "Espion", max_copies: 1, description: "Agile. Espion : Placé chez l'adversaire, piochez 2 cartes. Héros.", isHero: true },
    { id: 97, nom: "Letho de Gulet", royaume: "Nilfgaard", force: 10, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Un Héros.", isHero: true },
    { id: 98, nom: "Cahir Mawr Dyffryn", royaume: "Nilfgaard", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Un Héros.", isHero: true },
    { id: 99, nom: "Menno Coehoorn", royaume: "Nilfgaard", force: 10, type: "Unité", ligne: ["Siege"], capacite: "Médecin", max_copies: 1, description: "Médecin : Ramène une unité non-Héros de la défausse.", isHero: false },
    // AGILE
    { id: 100, nom: "Sorcier Nilfgaardien", royaume: "Nilfgaard", force: 6, type: "Unité", ligne: ["Ranged", "Siege", "Agile"], capacite: "Morale", max_copies: 2, description: "Agile. Morale : +1 de force à toutes les autres unités de sa rangée.", isHero: false },
    { id: 101, nom: "Garde Impériale", royaume: "Nilfgaard", force: 3, type: "Unité", ligne: ["Melee", "Ranged", "Agile"], capacite: "Lien Fraternel", max_copies: 3, description: "Agile. Lien Fraternel.", isHero: false },
    { id: 102, nom: "Fantassin Nilfgaardien", royaume: "Nilfgaard", force: 2, type: "Unité", ligne: ["Melee", "Ranged", "Agile"], capacite: "Aucune", max_copies: 3, description: "Agile. Unité de base.", isHero: false },
    { id: 103, nom: "Baliste Nilfgaardienne", royaume: "Nilfgaard", force: 5, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 104, nom: "Catapulte Nilfgaardienne", royaume: "Nilfgaard", force: 8, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 105, nom: "Arbalétrier d'élite", royaume: "Nilfgaard", force: 6, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 106, nom: "Chevalier de la Garde", royaume: "Nilfgaard", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 107, nom: "Médecin de l'Armée", royaume: "Nilfgaard", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Médecin", max_copies: 2, description: "Médecin : Ramène une unité non-Héros de la défausse.", isHero: false },
    { id: 108, nom: "Bélier Nilfgaardien", royaume: "Nilfgaard", force: 4, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 109, nom: "Brigade de Vrihedd", royaume: "Nilfgaard", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 110, nom: "Archer Nilfgaardien", royaume: "Nilfgaard", force: 3, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 111, nom: "Éclaireur Nilfgaardien", royaume: "Nilfgaard", force: 1, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 112, nom: "Cavalière Légère", royaume: "Nilfgaard", force: 2, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 113, nom: "Trébuchet Nilfgaardien", royaume: "Nilfgaard", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 114, nom: "Garde de l'Aube", royaume: "Nilfgaard", force: 7, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 115, nom: "Garde du Palatin (NG)", royaume: "Nilfgaard", force: 3, type: "Unité", ligne: ["Melee"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel.", isHero: false },
    { id: 116, nom: "Archer de l'Armée (NG)", royaume: "Nilfgaard", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Morale", max_copies: 2, description: "Morale.", isHero: false },
    { id: 117, nom: "Chevalier d'Élite", royaume: "Nilfgaard", force: 8, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 1, description: "Unité de base forte.", isHero: false },
    { id: 118, nom: "Garde Impériale (R)", royaume: "Nilfgaard", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 119, nom: "Catapulte de Camp", royaume: "Nilfgaard", force: 4, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 120, nom: "Ingénieur de Siège (NG)", royaume: "Nilfgaard", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 121, nom: "Fantassin (NG)", royaume: "Nilfgaard", force: 1, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 122, nom: "Éclaireur de la Garde (NG)", royaume: "Nilfgaard", force: 1, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 123, nom: "Arbalète Lourde (NG)", royaume: "Nilfgaard", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 124, nom: "Lancier Nilfgaardien", royaume: "Nilfgaard", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 125, nom: "Baliste de l'Armée", royaume: "Nilfgaard", force: 7, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 126, nom: "Officier de la Garde", royaume: "Nilfgaard", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 127, nom: "Unité de cavalerie", royaume: "Nilfgaard", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },

    // --- MONSTRES (ID 128 à 165) - 38 Cartes ---
    { id: 128, nom: "Eredin (Chasse Sauvage)", royaume: "Monstres", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Lien Fraternel)", max_copies: 1, description: "Chef. Ramène toutes les cartes de 'Lien Fraternel' de la défausse et les joue.", isHero: true },
    { id: 129, nom: "Eredin (Le Destructeur)", royaume: "Monstres", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Morale)", max_copies: 1, description: "Chef. Augmente la force de toutes les unités de sa ligne de 5.", isHero: true },
    { id: 130, nom: "Geralt de Riv (MO)", royaume: "Monstres", force: 15, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Héros. (Neutre - Duplication).", isHero: true },
    { id: 131, nom: "Ciri (MO)", royaume: "Monstres", force: 15, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Héros. (Neutre - Duplication).", isHero: true },
    { id: 132, nom: "Vampire Bruxa", royaume: "Monstres", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 3, description: "Ralliement : Pioche les copies du deck et les joue immédiatement.", isHero: false },
    { id: 133, nom: "Vampire Katakan", royaume: "Monstres", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 3, description: "Ralliement : Pioche les copies du deck et les joue immédiatement.", isHero: false },
    { id: 134, nom: "Goule", royaume: "Monstres", force: 2, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 3, description: "Ralliement : Pioche les copies du deck et les joue immédiatement.", isHero: false },
    { id: 135, nom: "Gargouille", royaume: "Monstres", force: 2, type: "Unité", ligne: ["Ranged"], capacite: "Ralliement", max_copies: 3, description: "Ralliement : Pioche les copies du deck et les joue immédiatement.", isHero: false },
    { id: 136, nom: "Griffon", royaume: "Monstres", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel.", isHero: false },
    { id: 137, nom: "Harpie", royaume: "Monstres", force: 4, type: "Unité", ligne: ["Ranged"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel.", isHero: false },
    { id: 138, nom: "Noyeur", royaume: "Monstres", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 139, nom: "Endriaga", royaume: "Monstres", force: 4, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 140, nom: "Fiellon", royaume: "Monstres", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 141, nom: "Élémentaire de Glace", royaume: "Monstres", force: 8, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 1, description: "Unité de base forte.", isHero: false },
    { id: 142, nom: "Wivern", royaume: "Monstres", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 143, nom: "Nekker", royaume: "Monstres", force: 2, type: "Unité", ligne: ["Melee"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel.", isHero: false },
    { id: 144, nom: "Spectre", royaume: "Monstres", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 145, nom: "Baliste Monstrueuse", royaume: "Monstres", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 146, nom: "Trébuchet Monstrueux", royaume: "Monstres", force: 7, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 147, nom: "Guerrier de la Chasse Sauvage", royaume: "Monstres", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel.", isHero: false },
    { id: 148, nom: "Vampire Fleder", royaume: "Monstres", force: 3, type: "Unité", ligne: ["Ranged"], capacite: "Ralliement", max_copies: 3, description: "Ralliement.", isHero: false },
    { id: 149, nom: "Géant de Glace", royaume: "Monstres", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 150, nom: "Golem de Pierre", royaume: "Monstres", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 151, nom: "Harpie des montagnes", royaume: "Monstres", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 152, nom: "Fantôme de la Chasse Sauvage", royaume: "Monstres", force: 3, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 153, nom: "Griffon Royal", royaume: "Monstres", force: 7, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 154, nom: "Banshee", royaume: "Monstres", force: 4, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 155, nom: "Vampire Ekimmara", royaume: "Monstres", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 3, description: "Ralliement.", isHero: false },
    { id: 156, nom: "Vampire Garkain", royaume: "Monstres", force: 4, type: "Unité", ligne: ["Ranged"], capacite: "Ralliement", max_copies: 3, description: "Ralliement.", isHero: false },
    { id: 157, nom: "Vampire Alp", royaume: "Monstres", force: 3, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 3, description: "Ralliement.", isHero: false },
    { id: 158, nom: "Guerrier des Glaces", royaume: "Monstres", force: 7, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 159, nom: "Endriaga Dronne", royaume: "Monstres", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 160, nom: "Ogre", royaume: "Monstres", force: 8, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 1, description: "Unité de base forte.", isHero: false },
    { id: 161, nom: "Trébuchet de guerre", royaume: "Monstres", force: 5, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 162, nom: "Guerrier Sauvage", royaume: "Monstres", force: 2, type: "Unité", ligne: ["Melee"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel.", isHero: false },
    { id: 163, nom: "Harpie des Mers", royaume: "Monstres", force: 4, type: "Unité", ligne: ["Ranged"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel.", isHero: false },
    { id: 164, nom: "Banshee Crieuse", royaume: "Monstres", force: 3, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 165, nom: "Élémentaire de Pierre", royaume: "Monstres", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },

    // --- SKELLIGE (ID 166 à 210) - 45 Cartes ---
    { id: 166, nom: "Crach an Craite (Chef)", royaume: "Skellige", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Ramener Mêlée)", max_copies: 1, description: "Chef. Ramène toutes les unités de la ligne de Mêlée dans le deck.", isHero: true },
    { id: 167, nom: "Bran Tuirseach (Chef)", royaume: "Skellige", force: 0, type: "Chef", ligne: "Melee", capacite: "Chef (Défausse)", max_copies: 1, description: "Chef. Pioche les 3 premières cartes de la défausse et en joue une.", isHero: true },
    { id: 168, nom: "Geralt de Riv (SK)", royaume: "Skellige", force: 15, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Héros. (Neutre - Duplication).", isHero: true },
    { id: 169, nom: "Ciri (SK)", royaume: "Skellige", force: 15, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Héros. (Neutre - Duplication).", isHero: true },
    { id: 170, nom: "Hjalmar an Craite", royaume: "Skellige", force: 10, type: "Unité", ligne: ["Melee"], capacite: "Héros", max_copies: 1, description: "Un Héros.", isHero: true },
    { id: 171, nom: "Kambi", royaume: "Skellige", force: 10, type: "Unité", ligne: ["Ranged"], capacite: "Héros", max_copies: 1, description: "Un Héros.", isHero: true },
    { id: 172, nom: "Cerys", royaume: "Skellige", force: 10, type: "Unité", ligne: ["Melee"], capacite: "Résurrection", max_copies: 1, description: "Héros. Résurrection : Ramène une unité de la défausse.", isHero: true },
    { id: 173, nom: "Guerrier Skellige", royaume: "Skellige", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Soif de Sang", max_copies: 3, description: "Soif de Sang : Double sa force si l'adversaire a plus de cartes dans sa défausse.", isHero: false },
    { id: 174, nom: "Médecin Skellige", royaume: "Skellige", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Médecin", max_copies: 2, description: "Médecin : Ramène une unité non-Héros de la défausse.", isHero: false },
    { id: 175, nom: "Jeune Berserker", royaume: "Skellige", force: 2, type: "Unité", ligne: ["Melee"], capacite: "Transformation", max_copies: 3, description: "Transformation : Se transforme en 'Berserker' (Force 8) si joué avec la capacité du Chef ou Meteo.", isHero: false },
    { id: 176, nom: "Vétéran Jarl", royaume: "Skellige", force: 8, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 177, nom: "Berserker", royaume: "Skellige", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Transformation", max_copies: 3, description: "Transformation : Se transforme en 'Berserker Enragé' (Force 8) si joué avec la capacité du Chef ou Meteo.", isHero: false },
    { id: 178, nom: "Jarl", royaume: "Skellige", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 2, description: "Ralliement : Pioche une carte Unité de votre deck et la joue immédiatement.", isHero: false },
    { id: 179, nom: "Archer Skellige", royaume: "Skellige", force: 3, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 180, nom: "Épéiste de la Garde", royaume: "Skellige", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 181, nom: "Navire de Guerre", royaume: "Skellige", force: 5, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 182, nom: "Jument des Vagues", royaume: "Skellige", force: 2, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 183, nom: "Baliste Skellige", royaume: "Skellige", force: 6, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 184, nom: "Ours Furieux", royaume: "Skellige", force: 8, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 185, nom: "Guerrier de la Harpie (SK)", royaume: "Skellige", force: 4, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 186, nom: "Chasseur de Monstre", royaume: "Skellige", force: 1, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 187, nom: "Vétéran de Guerre", royaume: "Skellige", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 2, description: "Ralliement.", isHero: false },
    { id: 188, nom: "Skald", royaume: "Skellige", force: 2, type: "Unité", ligne: ["Ranged"], capacite: "Médecin", max_copies: 2, description: "Médecin.", isHero: false },
    { id: 189, nom: "Skelle", royaume: "Skellige", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel.", isHero: false },
    { id: 190, nom: "Guerrier du Clan Drummond", royaume: "Skellige", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Soif de Sang", max_copies: 3, description: "Soif de Sang.", isHero: false },
    { id: 191, nom: "Lancier du Clan an Craite", royaume: "Skellige", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 192, nom: "Trébuchet Skellige", royaume: "Skellige", force: 7, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 193, nom: "Bélier Skellige", royaume: "Skellige", force: 4, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 194, nom: "Chasseur de Trolls", royaume: "Skellige", force: 8, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 1, description: "Unité de base forte.", isHero: false },
    { id: 195, nom: "Arbalétrier", royaume: "Skellige", force: 5, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 196, nom: "Garde du Jarl", royaume: "Skellige", force: 3, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 197, nom: "Éclaireur de la Garde (SK)", royaume: "Skellige", force: 1, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 198, nom: "Vétéran du Clan Tuirseach", royaume: "Skellige", force: 7, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 199, nom: "Baliste de l'Armée (SK)", royaume: "Skellige", force: 7, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 200, nom: "Archer de Siège (SK)", royaume: "Skellige", force: 3, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 201, nom: "Guerrier des Iles", royaume: "Skellige", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel.", isHero: false },
    { id: 202, nom: "Officier Skellige", royaume: "Skellige", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 203, nom: "Bélier de guerre (SK)", royaume: "Skellige", force: 5, type: "Unité", ligne: ["Siege"], capacite: "Lien Fraternel", max_copies: 3, description: "Lien Fraternel.", isHero: false },
    { id: 204, nom: "Guerrier de la Harpie (R)", royaume: "Skellige", force: 4, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 3, description: "Unité de base.", isHero: false },
    { id: 205, nom: "Navire de Guerre (R)", royaume: "Skellige", force: 5, type: "Unité", ligne: ["Siege"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 206, nom: "Épéiste de la Garde (R)", royaume: "Skellige", force: 6, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 207, nom: "Archer de Siège (R)", royaume: "Skellige", force: 3, type: "Unité", ligne: ["Ranged"], capacite: "Aucune", max_copies: 2, description: "Unité de base.", isHero: false },
    { id: 208, nom: "Vétéran de Guerre (R)", royaume: "Skellige", force: 5, type: "Unité", ligne: ["Melee"], capacite: "Ralliement", max_copies: 2, description: "Ralliement.", isHero: false },
    { id: 209, nom: "Skald (R)", royaume: "Skellige", force: 2, type: "Unité", ligne: ["Ranged"], capacite: "Médecin", max_copies: 2, description: "Médecin.", isHero: false },
    { id: 210, nom: "Berserker Enragé", royaume: "Skellige", force: 8, type: "Unité", ligne: ["Melee"], capacite: "Aucune", max_copies: 3, description: "Forme transformée du Jeune Berserker.", isHero: false },

    { id: 211, nom: "Chasse Sauvage Cavalier", royaume: "Monstres", force: 2, type: "Unité", ligne: ["Melee"], capacite: "Nuée", max_copies: 3, description: "Nuée : Cherche et joue toutes les cartes du même nom dans la rangée.", isHero: false },
    { id: 212, nom: "Nécrophage", royaume: "Monstres", force: 4, type: "Unité", ligne: ["Melee"], capacite: "Nuée", max_copies: 3, description: "Nuée : Cherche et joue toutes les cartes du même nom dans la rangée.", isHero: false },
    { id: 213, nom: "Brouillard Brumeux", royaume: "Monstres", force: 4, type: "Unité", ligne: ["Ranged"], capacite: "Nuée", max_copies: 3, description: "Nuée : Cherche et joue toutes les cartes du même nom dans la rangée.", isHero: false },


];

window.gwentCardData = gwentCardData ;